### ISSUE TITLE
Problem with inheritance and custom routes

### ISSUE THREAD

**Issue by vincenttheeten** [apiguy/flask-classy#22]
``` python
class BaseView(FlaskView):
    route_base = ''  # overwritten in deriving classes

    # additional shared routes here
    # /my_id/byText/findthistext
    def byText(self, text):
        # byText implementation omitted from this example
        pass

class ItemView(BaseView):
    route_base = '/items'

    @route(route_base + '/<id>/delete')
    def delete(self, id):
        # custom delete handler for items
        print 'Do delete'
        return 'success'
```

I'm getting a problem when defining custom routes (via the decorator) on inherited view classes.

When I go to /items/my_id/delete I get a response "301 Permenantly removed"

When the same delete method is added in the BaseView, it works perfectly.

Are there any limitations with view inheritance that we should be aware of?

**Comment by apiguy** [comment]
sorry for the delay on this @vincenttheeten I'll take a look at this tonight.

**Comment by DeaconDesperado** [comment]
It's been awhile since I checked into the latest release of flask-classy, but I think it's worth mentioning this:  Have you tried your routes with trailing slashes and checked your settings for [strict slashes?](http://werkzeug.pocoo.org/docs/routing/#rule-format)  This can get a little confusing in the Werkzeug spec re: 301 redirects and might be the same problem if we're preserving this default behavior.

**Comment by CaseyMilford** [comment]
@apiguy, have you found anything regarding this issue?  I'm experiencing the same.  Any time I set a route in a child class, it essentially hides all non-builtin routes in the parent class.  e.g., :index will continue to work.  If I remove the route decorators in the child, none of the child methods work, but the base is fully available again.

**Comment by apiguy** [comment]
I've got some tests now for this scenario and it seems to be working with the current codebase, see 

https://github.com/apiguy/flask-classy/commit/718186d94020c7de1c8872e648cc286096583cbc and https://github.com/apiguy/flask-classy/commit/fefbe1ba76a61fc7c321a291a1698df08f731edb

**Comment by ivan-kleshnin** [comment]
I still see a couple of problems:

``` python
from flask import Flask, Blueprint
from flask.ext.classy import FlaskView, route


class BasicView(FlaskView):
    @route('/create', methods=['GET', 'POST'])
    def create(self, id):
        pass

    @route('/detail/<id>')
    def detail(self, id):
        pass

    @route('/edit/<id>', methods=['GET', 'POST'])
    def edit(self, id):
        pass

    @route('/delete/<id>', methods=['GET', 'POST']) # (*)
    def delete(self, id):
        pass

class QuotesView(BasicView):
    @route('test')
    def test(self):
        pass


app = Flask(__name__)
blueprint = Blueprint('something', __name__)
QuotesView.register(blueprint)
app.register_blueprint(blueprint)

print app.url_map

Map([<Rule '/quotes/test' (HEAD, OPTIONS, GET) -> something.QuotesView:test>, # invalid methods          
 <Rule '/quotes/create/<id>' (HEAD, OPTIONS, GET) -> something.QuotesView:create>, # invalid methods            
 <Rule '/quotes/detail/<id>' (HEAD, OPTIONS, GET) -> something.QuotesView:detail>, # invalid methods                
 <Rule '/quotes/edit/<id>' (HEAD, OPTIONS, GET) -> something.QuotesView:edit>, # invalid methods                    
 <Rule '/quotes/<id>' (OPTIONS, DELETE) -> something.QuotesView:delete>,  # # invalid methods and URL
 ...
])
```
