### ISSUE TITLE
wrapped index and wrapped get will always default to get

### ISSUE THREAD

**Issue by shuhaowu** [apiguy/flask-classy#23]
If you use some sort of wrapper for the get and index functions, any attempt to call (request with a GET request) `index` will result calling `get`.

```
class SomeView(FlaskView):
  @login_required
  def get(self, id):
    pass  

  @login_required
  def index(self):
    pass
```

Note `login_required` is from flask-login.

**Comment by apiguy** [comment]
This is correct. As stated in the documentation, "special" methods have default behavior. `index` and `get` are special methods and have the default behavior of being accessible via the `GET` verb. If you wish to override this you may do so by using the `route` decorator provided with FlaskClassy.

**Comment by shuhaowu** [comment]
But requesting `GET /some/` will result in the `get` function being called. 

If i remove the decorator, `index` will be called instead. That's my issue.

**Comment by apiguy** [comment]
Ah I see. Are you using dev or did you a straight pip install?

**Comment by shuhaowu** [comment]
pip

**Comment by apiguy** [comment]
Ok. I don't have a test case for this yet, it would be awesome if you could submit one. I've actually been working in the decorators support recently so I might be able to get a fix out for this.

**Comment by shuhaowu** [comment]
I'm not too familiar with the code base yet. I don't have time at the moment to look into it. Turns out I don't need to implement this just yet. I'll look into it when I get a chance later.

I have another bug report coming, too.

**Comment by apiguy** [comment]
Ok. Thanks @shuhaowu I'll take a look soon.

**Comment by shuhaowu** [comment]
I'm ready to fix this. Any ideas what might be wrong with this? I would appreciate any insight/pointers :+1:

**Comment by apiguy** [comment]
I think I've found a way to get the true argspec of the underlying method regardless of the decorator used but I need to investigate a bit more to ensure it's reliable. Basically the approach is to inspect the closure cells, find a function inside that has an argspec who's args begins with `self`. So far it works great but I'm sure there are some edge cases where it's not going to be so easy and I'm trying to figure out what those are before I push something.

**Comment by apiguy** [comment]
Ok this seems to work for most of the (reasonable) cases I can come up with. I'm feeling the need to add more tests but I think the result of that will simply be that I'll discover more edge cases that could be supported with some small changes to the `get_true_argspec` function added in 7ae3d75.

@shuhaowu If you can - please test this and see if it works for you.

**Comment by shuhaowu** [comment]
Works. Good work! :+1:
