### ISSUE TITLE
Do not auto add trailing slash

### ISSUE THREAD

**Issue by shuhaowu** [apiguy/flask-classy#24]
This might be a more controversial change... but trailing slashes are not automatically added for flask itself unless specified.

A 301 redirect also consumes bandwidth and CPU (I remember reading an article that measured 30% of its time spent in 301 redirects due to 1 missing /. Can't find that article right now, though).

**Comment by DeaconDesperado** [comment]
We had this issue once previously, #4 

The decision was to use the directory/resource approach that is implicit in HTTP.  The idea is that a trailing slash  route could conceivably be a "grouping" or directory of resources whereas a route without one is implicitly a single "file" or entity.  It is a comfortable convention that encourages good design for REST.

**Comment by shuhaowu** [comment]
I understand that for things like the base url (SomeView -> /some/) might be a directory. However, when you define a custom function (`def custom(): ...`), that should be a file unless otherwise stated as not a file. Right? That's how I see it at least.

**Comment by apiguy** [comment]
I'm pretty sure this was addressed but it's not in the cheese shop at the moment. Look at: https://github.com/apiguy/flask-classy/commit/02b84ef9963c9e99b90002fde5e75d00c82f235d 

Feel free to reopen if that wasn't the issue you were talking about though.
