### ISSUE TITLE
@route on two functions (post and index) with the same route will fail

### ISSUE THREAD

**Issue by shuhaowu** [apiguy/flask-classy#26]
Ideally, you would have one that goes into POST and one that goes into GET. 

```
class SomeView(FlaskView):
  @route("/route")
  def get(self, id):
    pass

  @route("/route")
  def index(self, id):
    pass
```

only one will work.

**Comment by apiguy** [comment]
I think the issue you're having is that you must supply a `methods` attribute when you use `@route` or the default value for `methods` will be used (which is `GET`). This behavior is consistent with `Flask`'s default behavior.

try using:

``` python

@route("/route", methods=['POST'])

```
