### ISSUE TITLE
Allow setting of cache control

### ISSUE THREAD

**Issue by mattotodd** [apiguy/flask-classy#27]
IE is cacheing all the returned responses from flask classy.  

Please allow for setting the cache control of default it to no_cache

example:

response.cache_control.no_cache = True

**Comment by apiguy** [comment]
Currently you can do this the same way as with normal views like:

``` python
resp = make_response(render_template(...))
resp.cache_control.no_cache = True
return resp
```

Also, you can do this in the `FlaskView`'s `after_<view_method>` or `after_request` methods:

``` python
class ArticleView(FlaskView):

    def get(self, id):
        return render_template(...)

    def index(self):
        return render_template(...)

    def after_get(self, response):
        # This only runs for the 'get' method
        response.cache_control.no_cache = True
        return response

    def after_request(self, name, response):
        # This runs for all methods in this class
        response.cache_control.no_cache = True
        return response
```

Does that work?

**Comment by mattotodd** [comment]
woah, didn't know about `after_request`, classic "Read the Docs" moment  thanks!
