### ISSUE TITLE
How do I use `url_for()`?

### ISSUE THREAD

**Issue by Blender3D** [apiguy/flask-classy#28]
I looked through both the documentation and the source, but I wasn't able to find anything relating to `url_for`. Let's say I have a simple class like this:

```
class UserViews(FlaskView):
    route_base = '/user/'

    @route('/<int:id>/')
    @route('/<int:id>/<username>/')
    def profile(self, id=None, username=None):
        user = User.query.get_or_404(id)

        if user.clean_username != username:
            return redirect(url_for('.profile', id=id, username=user.clean_username))

        return render_template('user/profile.html', user=user)
```

I was trying to use `url_for('.profile')` and `url_for('UserViews.profile')`, but neither of those worked. How do I replicate this functionality with a `FlaskView`?

Thanks!

**Comment by Blender3D** [comment]
Just noticed the `url_for`s in your [test cases](https://github.com/apiguy/flask-classy/blob/master/test_classy/test_endpoints.py). It might be helpful to others if you added a small section in the documentation about it.

**Comment by apiguy** [comment]
Thanks for the feedback, I'm adding it to the docs tonight to be include with the release.
