### ISSUE TITLE
`route_base` overlaps

### ISSUE THREAD

**Issue by ivan-kleshnin** [apiguy/flask-classy#30]
_`route_base` argument for `FlaskView.register` has unpleasant side-effect (changes `FlaskView` global state)_

**myflask/blog/**init**.py**

``` python
blueprint = Blueprint('blog', __name__)

class PostsView(flask.ext.classy.FlaskView):
   ...
```

**myflask/backend/**init**.py**

``` python
from .. import blog

blog.PostsView.register(blueprint, route_base='posts') # this `route_base`
```

**myflask/frontend/**init**.py**

``` python
from .. import blog

blog.PostsView.register(blueprint) # affects this if `route_base` argument is omitted
```

It can be walked around by sending `route_base` with **all** calls but this is an issue anyhow.

**Comment by apiguy** [comment]
Confirmed. Looks like I maintain state in the case where a route base was specified, but I don't maintain the state where a route base was not specified.

The fix is pretty easy for this - I just need to write some tests for it.

**Comment by apiguy** [comment]
This should be up on the cheese shop now.
