### ISSUE TITLE
Maximum recursion depth exceeded error when using certain decorators

### ISSUE THREAD

**Issue by dgilland** [apiguy/flask-classy#34]
I receive a `RuntimeError: maximum recursion depth exceeded` error:

``` bash
<...snip...>
  File "/temp/flask-classy-decorator-bug/env/local/lib/python2.7/site-packages/flask_classy.py", line 282, in get_true_argspec
    return get_true_argspec(method)
  File "/temp/flask-classy-decorator-bug/env/local/lib/python2.7/site-packages/flask_classy.py", line 282, in get_true_argspec
    return get_true_argspec(method)
  File "/temp/flask-classy-decorator-bug/env/local/lib/python2.7/site-packages/flask_classy.py", line 272, in get_true_argspec
    argspec = inspect.getargspec(method)
  File "/usr/lib/python2.7/inspect.py", line 816, in getargspec
    args, varargs, varkw = getargs(func.func_code)
  File "/usr/lib/python2.7/inspect.py", line 799, in getargs
    return Arguments(args, varargs, varkw)
RuntimeError: maximum recursion depth exceeded
```

with the following code:

``` python
from functools import wraps

from flask import Flask
from flask.ext.classy import FlaskView

app = Flask(__name__)

def test(a=1, b=2):
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kargs):
            decorated_function.foo()
            return f(*args, **kargs)

        def foo(*args, **kargs):
            return 'foo'

        decorated_function.foo = foo

        return decorated_function
    return decorator

class TestView(FlaskView):
    @test()
    def index(self):
        return "Hello World!"

if __name__ == "__main__":
    TestView.register(app)
    app.run(debug=True)
```

The line in the example that is causing the error is `decorated_function.foo()`.

It might seem odd to actually use a function like this, but my simple example is derived from using [Flask-Cache](https://github.com/thadeusb/flask-cache), specifically the `cache.cached()` decorator defined here: https://github.com/thadeusb/flask-cache/blob/master/flask_cache/__init__.py#L174.

So if you were to replace my example with a more practical one, then you'd have:

``` python
from flask import Flask
from flask.ext.classy import FlaskView
from flask.ext.cache import Cache

app = Flask(__name__)
cache = Cache(app)

class TestView(FlaskView):
    @cache.cached()
    def index(self):
        return "Hello World!"

if __name__ == "__main__":
    TestView.register(app)
    app.run(debug=True)
```

which also results in the maximum recursion error.

I'm using the following versions:
- Python==2.7.3
- Flask==0.10.1
- Flask-Cache==0.12
- Flask-Classy==0.6.3

**Comment by apiguy** [comment]
Interesting. Looks like this comes from the code I'm using to drill down to find the base signature of the method. I should be able to check if the method/function I'm inspecting is the same as the one I'm coming from and then skip it.

**Comment by schleppy** [comment]
I have this same issue and it stems from the `@cache.cached()` decorator.  I was able to get around it by modifying the `get_true_argspec` method but it seems that the big feature I really wanted with the latest version (allowing for route inheritance) fails with my change.  Hopefully an elegant solution that handles this issue is coming.  I will try my hand at it again tomorrow.

**Comment by johnjiang** [comment]
This seems to be fixed in the latest version of flask-classy. Tested on 0.6.8 and don't get the maximum recursion depth exception.
