### ISSUE TITLE
Don't add trailing slash to routes

### ISSUE THREAD

**Issue by xintron** [apiguy/flask-classy#4]
When defining custom routes with `routes` a trailing slash is added.

``` python
class TestView(FlaskView):
    @route('/foo', methods=['POST'])
    def foo(self):
        return 'foo'
```

This adds a trailing slash to the making the route: `/test/foo/` causing a
redirect when doing a post to `/test/foo`.

**Comment by apiguy** [comment]
I actually went back and forth on this for what the "default" behavior should be when configuring routes. What's your feeling on the auto-generated routes? I chose to default to a trailing slash because flask will automatically fix the path if you miss the trailing slash, (by way of a redirect, as you mention) but will 404 the other way around. I like the safety of the approach, but I do feel like being explicit might be better.

Here are some options, tell me what you think:
1. Change the default behavior to no-slash
2. Leave the default behavior, but honor no-slash `route` decorators
3. Create a configuration value that defines which behavior you prefer

or of course some combination...

**Comment by xintron** [comment]
One thing should be changed at least, the second suggestion. When adding
a route with the decorator it should not append a trailing slash (and as
you say give a 404 if you try to access that route with a trailing
slash).

I think it would be great with a configuration-option to set the default
solution for auto-generated routes but that should only be valid for
auto-generated, not when you set a route with the decorator (then the
decorator-value should always be used in conjunction with the class-base
route ofc).

**Comment by DeaconDesperado** [comment]
Freedom,

I'm working on implementing your ext in our internal API, so I've been
collecting thoughts to send later, just want to weigh in on this real
quick...

A DELETE request totally breaks on using this behavior in debug mode, which
makes local API testing a bit of a pain.  Flask raises its
FormDataRoutingRedirect exception to make certain the routes are reliably
set for DELETE, which makes sense I suppose.

I think it would probably be best to assume no trailing slashes on the
four, method-named core methods of classy.  They generally must end with
GUIDs of some sort anyway ('/models/iam_am_a_GUID') or in the case of
creates from CRUD just the path itself ('/models' POST).  I think it should
be configurable but in light of the way Flask does these form redirects I
feel it should assume no trailing slash where it isn't explcitly intended.

Mark

**Comment by apiguy** [comment]
Thanks Mark that's really good feedback. I've been discussing with some other colleagues and generally my sense is that most developers feel the same as you, so I'll be making that change.

This could be a breaking change for some existing users, and I've got one other "potentially" breaking change to implement as well so I think I'll put them together and get a release out that addresses both.

Thanks for the feedback it helps to hear what users actually need/want when building these things :)

**Comment by xintron** [comment]
I like the way they put it in the Flask documents about seeing URLs ending with a trailing slash as a "folder" on a filesystem and URLs without trailing slash as files. Based on that view I would vote for generating the following defaults as follows:

```
POST: /<classname>/ - Create a new post
GET: /<classname>/ - Get a list of posts
GET: /<classname>/<id> - Get a specific post, no trailing slash, treat it as a file
PUT/PATCH/DELETE: /<classname>/<id> - Update/patch/delete the post, no trailing slash
```

Those are just my two cents.

**Comment by apiguy** [comment]
@xintron Yup that is exactly what I needed to get the decision made. I'm changing the default to that, and allowing for overrides in the route decorator.

**Comment by apiguy** [comment]
Alright this change is there and pushed up to the cheese shop, version 0.5.

**Comment by utsengar** [comment]
Just an FYI, if you are trying to rely on the function name as the route and not specify a `@route('/show')`, flask-classy still redirects no trailing slash to a trailing slash URL.

Example:

This function if accessed via http://host/show , it will redirect to http://host/show/

```
def show(self):
      pass
```

But this function won't, this will give a 404 if http://host/show/ is accessed:

```
@route('/show')
def show(self):
      pass
```

Where `route` is `from flask.ext.classy import route`

**Comment by etscrivner** [comment]
Second what @utkarsh2012 said. This is pretty obnoxious and unexpected.

**Comment by joest67** [comment]
Just set `Content-typ` with `application/json`, it works for API Web Application.
