### ISSUE TITLE
Support for http methods other than GET on custom methods

### ISSUE THREAD

**Issue by ryanlowe0** [apiguy/flask-classy#71]
One of the main reasons I like Flask-Classy over Flask-Restful is the support for custom methods, allowing endpoints to be grouped in the same class. But, as far as I can tell, all custom methods are GET only. 

So, first, is there currently any way to make a custom method be, say, POST instead of GET that I am missing? Second, if not, are there any plans to support this? 

I have only just started working with Classy, but my first thought was to add a check for a prefix, e.g. "def post_my_custom_method(self)", which would route to /my_custom_method/ with method POST.

**Comment by ghost** [comment]
As far as I know it's like in the Flask core:

```
@route('/custom/route/', methods=['POST'])
def custom_method(self):
    pass
```

HTTP decorators like in bottle.py aren't integrated. If the `methods` parameter isn't the one you're looking for, you could implement your owns.

**Comment by ryanlowe0** [comment]
Oh cool, that ought to suffice. Thanks!
