### ISSUE TITLE
SyntaxError on 0.5 release

### ISSUE THREAD

**Issue by maxcountryman** [apiguy/flask-classy#8]
```
>>> from flask.ext.classy import FlaskView
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/max/Desktop/.../virtualenv/lib/python2.6/site-packages/flask/exthook.py", line 61, in load_module
    __import__(realname)
  File "/Users/max/Desktop/.../virtualenv/lib/python2.6/site-packages/flask_classy.py", line 101
    options = {k:v for k,v in options.iteritems() if k != "endpoint"}
                     ^
SyntaxError: invalid syntax
```

**Comment by apiguy** [comment]
Thanks Max. I shouldn't have used a dictionary generator there (I forgot they aren't available in python versions earlier than 2.7). I'll get a fix in for that.

**Comment by maxcountryman** [comment]
I can send a patch your way if that works.

**Comment by apiguy** [comment]
if you've got one that would be awesome.

**Comment by apiguy** [comment]
I think you might be a version behind - in 0.5.1 you'll find the offending line is 137 instead of 101

**Comment by maxcountryman** [comment]
Thanks, I was a version behind and I did find the proper line. :)

**Comment by apiguy** [comment]
@maxcountryman I had to make a slight modification. A copy of the original dictionary needs to be made or the test for custom endpoints will fail. I'm not sure if I've got a dangling reference or if the dangling reference is in Flask itself. I'll look at it more to figure out where it is. For now though the dict copy is required to get custom endpoints to work.

**Comment by maxcountryman** [comment]
Okay sounds good. Your generator exp was creating a new dict for you so I'm guessing that's why it worked before. In any case, should be fine to `copy()` it.

**Comment by apiguy** [comment]
Yeah IIRC when I first wrote it I did use `pop` however I hit that issue with the test cases, then went to the generator (partially out of a bit of frustration). I'm not certain that `copy` is beter than iterating over the dict but I do like that it's less code and clearer.

**Comment by maxcountryman** [comment]
Btw, not that it makes much difference, but you can call the `copy()` method on the dictionary object instead of: `copy.copy`. (Does exactly the same thing, makes a shallow copy.)

**Comment by apiguy** [comment]
Hey nice! I've already sent our latest work up to the cheese shop but I'll make that adjustment for the next release.

**Comment by maxcountryman** [comment]
Also `pop` should be _slightly_ more performant:

```
$ python -m timeit -s "d = dict(zip(range(10000), range(10000))); e = d.copy(); a = e.pop('foo', None); b = e.pop('bar', None)"
100000000 loops, best of 3: 0.0156 usec per loop

$ python -m timeit -s "d = dict(zip(range(10000), range(10000))); d = {k: v for k, v in d.iteritems() if k not in ['foo', 'bar']}"
100000000 loops, best of 3: 0.0157 usec per loop
```

Basically negligible: the original bench I used wasn't correct. Still given what that the keys are needed and shouldn't be in the final dict and compatibility and readability, I think `pop` is probably the better idiom.

**Comment by apiguy** [comment]
Yep that's definitely faster. Hopefully nobody's options dict gets that big though! I like `pop` because I think it's clearer to read. Much more obvious that we're yoinking those values out of the dict.
