### ISSUE TITLE
Please add trailing slashes after parameters in GET method

### ISSUE THREAD

**Issue by acimnotes** [apiguy/flask-classy#87]
Greetings! The GET default route doesn't add trailing slashes after parameters even if I add this option to the `MyView.register(app, trailing_slash=True)`method. I need trailing slashes for Flask-Freezer extension to generate static pages. I've solved this for now by putting the decorator like so: `@route('/<int:f_id>/')` but I would love to know how to make it work automatically. Please help me guys?

**Comment by hoatle** [comment]
@Arkturian we've released https://github.com/teracyhq/flask-classful v0.14.0 with the support for your case by this issue https://github.com/teracyhq/flask-classful/issues/47
