### ISSUE TITLE
Tagged releases would be nice

### ISSUE THREAD

**Issue by maxcountryman** [apiguy/flask-classy#9]
Having some trouble pairing hashes with releases. It'd be nice if this project were to tag releases on the repo.

**Comment by apiguy** [comment]
I agree completely. I'm a recent convert from Mercurial so there are a lot of corners of `git` I'm not currently familiar with, specifically around best-practices for release management.

In Mercurial, I could simply tag a commit, but it seems that in git it may be more common to keep a separate release branch and tag that. Does that sound right?

**Comment by maxcountryman** [comment]
You don't necessarily have to have a separate branch. I tag against master with rauth and that seems to be working pretty well. Basically when I feel like things are looking good for a release on master, I tag it with a version number, push the tags to GitHub and then do sdist. Feel free to poke around that project if it helps. :)

**Comment by apiguy** [comment]
Awesome. Got it. There's a v0.5.2 tag up there now.

**Comment by maxcountryman** [comment]
Cool, thanks!
